spring:
  datasource:
    url: jdbc:mysql://db:3306/taskManager?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

  management:
    endpoints:
      web:
        exposure:
          include: info, health, metrics